# Generated by Django 4.2.4 on 2023-08-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
