# Generated by Django 4.2.4 on 2023-09-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_nickname_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Nickname'),
            preserve_default=False,
        ),
    ]
